### ISSUE TITLE
Error occurs when creating a project to overwrite a different type of project

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-spring-initializr#108]
**Environments**

- OS: Windows 10/OS X
- VS Code version: 1.30.2
- Extension version Build RC/2

**To Reproduce**
1. Generate a Maven Project.
2. Generate a Gradle Project with a same artifactId and folder.
3. Then show a warning message:
    
&emsp;&emsp;![image](https://user-images.githubusercontent.com/41051257/51464059-b5e1f200-1d9f-11e9-9603-c08d6a9d9098.png)

4. Click continue button.
5. See error.

**Current behavior**

&emsp;&emsp;![image](https://user-images.githubusercontent.com/41051257/51464294-30ab0d00-1da0-11e9-86f0-1d7f003a28ad.png)

**Expect behavior**

&emsp;&emsp;![image](https://user-images.githubusercontent.com/41051257/51464751-4b31b600-1da1-11e9-87b4-d0ef7514858d.png)

This issue also reproduce on previous version.

**Comment by Eskibear** [comment]
by design.
