### ISSUE TITLE
Générate spring boot package files

### ISSUE THREAD

**Issue by zied-guesmi** [microsoft/vscode-spring-initializr#115]
Is it possible to add support for generating spring boot files (service, controller, repository...) in a folder according to its name?

**Comment by Eskibear** [comment]
Currently it serves as a shortcut to the spring initializr, as the name says. 
For the feature you mentioned, can you be more specific? Or is it already implemented in other Editor/IDEs? According to the description above, currently I guess [vscode-spring-boot](https://github.com/spring-projects/sts4/tree/master/vscode-extensions/vscode-spring-boot) would be the right place for it.
