### ISSUE TITLE
Unable to create project

### ISSUE THREAD

**Issue by chinesesoule** [Microsoft/vscode-spring-initializr#116]
![1](https://user-images.githubusercontent.com/22019999/53654829-a6e93c00-3c89-11e9-9232-7bb08bd9f5e5.gif)
![4nuth31m1i 6o7fq2hoj4 p](https://user-images.githubusercontent.com/22019999/53654879-c2ecdd80-3c89-11e9-9698-35073fcc2393.png)

**Comment by Eskibear** [comment]
When fetching versions, it actually sends HTTP GET request to `https://start.spring.io/` or your custom service url. Looks the response is not in JSON format. 
Are able to visit the service URL https://start.spring.io/ ? What if you send HTTP GET request with header `Accept: "application/vnd.initializr.v2.1+json"`?

**Comment by chinesesoule** [comment]
Hello, I can access https://start.spring.io/ in the browser. At the same time, I use java program to initiate http get request to https://start.spring.io/ and add the header Accept:"applicationvnd .initializr.v2.1json" The returned data format is json format. The data format returned when I did not add a header request is also in json format. This plugin was available to me before but it appears after I reinstalled vscode. This problem

**Comment by chinesesoule** [comment]
I tried it again today and I can use it normally.

**Comment by kilmercr** [comment]
Guys,

I try to solve this problem, but nothing that i tried make it happen. Can u help me?

I use Linux/Ubuntu at my Job and I dont have root permission to re-install the vscode.
Then, I removed the folders created under my user home to restart all configuration. I re-install all extensions again and it continue doesn't work.

**Comment by Eskibear** [comment]
It's probably because the response is html format instead of json format, as mentioned in https://github.com/Microsoft/vscode-spring-initializr/issues/116#issuecomment-468933922

E.g. when you `JSON.parse` following content, it has the same error:
```
"<!doctype html>..."
 ^
 |
 position 0
```

**Comment by kilmercr** [comment]
Ok, I got it...
But, there any place in VSCODE (any file or settings) that I can configure it fix and solve this bug?

**Comment by Eskibear** [comment]
@kilmercr You may check proxy settings in VSCode, etc. Before that, I just made a private build, which prints out raw response whenever JSON.parse fails. See https://github.com/Microsoft/vscode-spring-initializr/issues/119#issuecomment-481982681 
Find the output in Developer Tools view. 

Sorry for the delay. (the closed issue is hard to track)
