### ISSUE TITLE
Fail to create a project. Error: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by thomas0927** [Microsoft/vscode-spring-initializr#119]
Issue Type: <b>Bug</b>

Fail to create a project. Error: Unexpected token < in JSON at position 0

Extension version: 0.4.5
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.22GB (0.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Eskibear** [comment]
Similar issue here #116 .

**Comment by Eskibear** [comment]
What's the response if you send a request following https://github.com/Microsoft/vscode-spring-initializr/issues/116#issuecomment-468933922

**Comment by thomas0927** [comment]
Hi Eskibear, I got the response :Fail to create a project. Error: Unexpected token < in JSON at position 0.
It's same issue as #116 ,please help me to fix it.

**Comment by Eskibear** [comment]
Actually I mean the http response...

Never mind, you can unzip and install the following private package, which prints out the raw data in developer tools view. Let's see what's happening.
[vscode-spring-initializr-0.4.5.vsix.zip](https://github.com/Microsoft/vscode-spring-initializr/files/3067188/vscode-spring-initializr-0.4.5.vsix.zip)

**Comment by thomas0927** [comment]
How show I use this zip file? it can't be run to setup!

**Comment by thomas0927** [comment]
or should i put it in which folder?

**Comment by Eskibear** [comment]
- Unzip it, you get a .vsix file. 
- Open VSCode, click "...", click "Install from VSIX" 
<img width="578" alt="Screen Shot 2019-04-11 at 2 40 48 PM" src="https://user-images.githubusercontent.com/2351748/55936066-d2d3e600-5c67-11e9-9815-ec50039574c8.png">

**Comment by thomas0927** [comment]
![image](https://user-images.githubusercontent.com/4996949/55936441-ee8bbc00-5c68-11e9-9d8c-e5578c732081.png)
how should I bring the response info to you? I didn't find any diff.

**Comment by Eskibear** [comment]
@thomas0927 Open the "Developer Tools" view, you'll see the message.

**Comment by Nukepayload2** [comment]
![image](https://user-images.githubusercontent.com/10798596/57593509-4ff7c100-756e-11e9-9c90-bcdbc78c2c63.png)
Any updates on this issue? How can I configure the spring-initializr extension to bypass the captcha page of https://start.spring.io/ ?

**Comment by Eskibear** [comment]
@Nukepayload2 The extension calls the [official APIs](https://docs.spring.io/initializr/docs/current/reference/html/#api-guide) to fetch metadata, which is not supposed to involve the captcha stuffs. You may use the private build mentioned [above](https://github.com/microsoft/vscode-spring-initializr/issues/119#issuecomment-481982681) to see raw response. Can you double check on it?

**Comment by SailHe** [comment]
My problem here is the network environment, it may have been hijacked
Change an IP address will work
