### ISSUE TITLE
no response and long recycle progress

### ISSUE THREAD

**Issue by yinqp** [microsoft/vscode-spring-initializr#120]
Issue Type: <b>Bug</b>

progress at long time that Downloading zip package... where centos7 + openjdk8

Extension version: 0.4.5
VS Code version: Code 1.35.1 (c7d83e57cd18f18026a8162d042843bda1bcf21f, 2019-06-12T14:27:31.086Z)
OS version: Linux x64 3.10.0-957.el7.x86_64

**Comment by Eskibear** [comment]
Probably some bug that wrongly swallows exceptions, and it doesn't update the status after that. 

But I cannot reproduce it. Are you continueously experiencing that? If you can stably reproduce it, please share the steps so we can help to investigate. 
BTW it doesn't matter with the jdk version, here the logic is merely nodejs code.
