### ISSUE TITLE
After generating folder is not opened in VS Code

### ISSUE THREAD

**Issue by Power-tile** [microsoft/vscode-spring-initializr#130]
Issue Type: <b>Feature Request</b>

After generating a project using the Spring Initializr, VS Code didn't automatically open up the folder generated. Manual opening is required instead. Pretty unfriendly to users.

Extension version: 0.4.6
VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
OS version: Windows_NT x64 10.0.18362

**Comment by Eskibear** [comment]
It should pop up a notification, and you can choose whether to open it in current window/ a new window / as a workspace folder.

**Comment by Vlastimil157** [comment]
> Issue Type: Feature Request
> 
> After generating a project using the Spring Initializr, VS Code didn't automatically open up the folder generated. Manual opening is required instead. Pretty unfriendly to users.
> 
> Extension version: 0.4.6
> VS Code version: Code 1.40.2 (f359dd69833dd8800b54d458f6d37ab7c78df520, 2019-11-25T14:54:45.096Z)
> OS version: Windows_NT x64 10.0.18362
