### ISSUE TITLE
Allow Project Metadata Options

### ISSUE THREAD

**Issue by rubensa** [microsoft/vscode-spring-initializr#131]
For now you can only specify this Project Metadata:

- Group
- Artifact

User should have the option to specify:

- Name
- Description
- Package name
- Packaging (Jar, War)
- Java (8, 11, 13)

as those options are available at https://start.spring.io/

**Comment by Eskibear** [comment]
VSCode lacks wizard-like UI, thus it's hard to let you specify all of them in a single page. We usethe default values for these options, so users can finish the project creation in fewer steps.

These options are easy to modify in your `pom.xml` or `build.gradle` files, after creating the project.

**Comment by rubensa** [comment]
The problem I see (apart from not been able to provide all options) is that this **extension** and **https://start.spring.io/** generates different defaults.

**https://start.spring.io/** generates this default:

- **Name** = **Artifact** (I think so as main class name is Artifact value in [Pascal Case](https://wiki.c2.com/?PascalCase))

While the extension generates this:

- **Name** = **Demo** (I think so as main class name is always **DemoApplication**)

PD:  I think there are not so much options so they could be asked without much problem (providing default values, as https://start.spring.io/ does)

**Comment by Eskibear** [comment]
>  this extension and https://start.spring.io/ generates different defaults.

I don't see that. I see below, the official site also generates "Demo". 
![image](https://user-images.githubusercontent.com/2351748/72085062-a573b000-333f-11ea-903a-bf550e519548.png)

> I think there are not so much options so they could be asked without much problem

As I said, in VS Code, with current UI, it's impossible for the user to modify an option (if wrongly typed). The user has to cancel it, and fill in all the options again. That's why we only keep as few options as possible.

**Comment by rubensa** [comment]
> I don't see that. I see below, the official site also generates "Demo".
> ![image](https://user-images.githubusercontent.com/2351748/72085062-a573b000-333f-11ea-903a-bf550e519548.png)

I mean if you set, for example "**spring-boot-java-app**" as **Artifact**, then the **Name** is also "automatically" changed to that value.
In the extension, if you specify the **Artifact** to "**spring-boot-java-app**" the **Name** is kept as "**demo**".

> As I said, in VS Code, with current UI, it's impossible for the user to modify an option (if wrongly typed). The user has to cancel it, and fill in all the options again. That's why we only keep as few options as possible.

Shouldn't it be possible to provide selectable default values for the other options as those provided in  https://start.spring.io/ (keeping in mind that, for example, **Name** selectable default should be based on previously set **Artifact**, and the **Package name** should be based on provided **Group** and **Artifact**)?  This way, If the user simply selects the default values the possible mistakes are minimized.

**Comment by Eskibear** [comment]
> I mean if you set, for example "spring-boot-java-app" as Artifact, then the Name is also "automatically" changed to that value.

This makes sense. 

> Shouldn't it be possible to provide selectable default values for the other options as those provided in https://start.spring.io/

One possible solution is like what you mentioned, adding input boxes for **Name** and **Package name** after **Group** and **Artifact** are provided, it automatically fill the default values, e.g. `Name = Artifact`, `PackageName = Group.Artifact`. 

> Packaging (Jar, War)
Java (8, 11, 13)

Actually we do allow you to speficy **Packaging**, see definition of setting [spring.initializr.defaultPackaging](https://github.com/microsoft/vscode-spring-initializr/blob/aa41b63a43e6a739c7e8c67217a21bc858bf4868/package.json#L111-L120). If it's empty, then you have to select Packaging each time you create a project. I think for option **Java**, we can also use the same mechanism.

**Comment by Eskibear** [comment]
Now with 'back' button added the in [v0.5.0](https://github.com/microsoft/vscode-spring-initializr/blob/master/CHANGELOG.md#050), we enabled all the options by default. So I'm closing it.
