### ISSUE TITLE
Support for Scala and SBT

### ISSUE THREAD

**Issue by ilovemysillybanana** [microsoft/vscode-spring-initializr#134]
Currently only Maven/Gradle and Kotlin, Groovy, and Java are selectable options.

**Comment by syte** [comment]
As someone who is also using Scala with Spring, this would be great :).

**Comment by Eskibear** [comment]
Browsing https://start.spring.io/ and searching for the [API](https://docs.spring.io/initializr/docs/current/reference/html/#api-guide), I don't find any options for Scala and SBT.
