### ISSUE TITLE
Specify the Java version when generating a new project

### ISSUE THREAD

**Issue by mfgabriel92** [microsoft/vscode-spring-initializr#136]
Using start.spring.io website I can specify the Java version to use, but not with the extension. It would be interesting to be able to do so, too.

**Comment by Eskibear** [comment]
In vscode, we have no wizard to use. Thus we only prompt to ask most important questions. Java version is relatively easy to change after project is created. E.g. For maven projects:
```xml
 <properties>
    <java.version>11</java.version>
  </properties>
```

**Comment by Eskibear** [comment]
supported in v0.5.0
