### ISSUE TITLE
Nothing is appearing after activating extension step happen

### ISSUE THREAD

**Issue by Sanket110297** [microsoft/vscode-spring-initializr#142]
Issue Type: <b>Bug</b>

Press **Ctrl+Shift+P**, try to make a spring boot project using maven, nothing will come .

Extension version: 0.4.8
VS Code version: Code 1.33.0 (0dd516dd412d42323fc3464531b1c715d51c4c1a, 2019-04-04T15:14:28.026Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.84GB (0.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Eskibear** [comment]
I cannot reproduce it. 

Can you provide more details? E.g. do you have some specific settings? Can you find any error logs after executing command `Developer: Toggle Developer Tools`

**Comment by Sanket110297** [comment]
Nothing is appering in the logs. **Activating extensions** appears first for some time after clicking **Spring Initializr : Generate a Maven Project** . Then everything back to base and nothing comes up with no error, no exceptions nothing.
