### ISSUE TITLE
Not prompt error message when connect site failed

### ISSUE THREAD

**Issue by ZhengJun003** [microsoft/vscode-spring-initializr#153]
### Environments

- OS: Windows 10/OS 10.15.3
- VS Code version: 1.48.0
- Extension version: 0.5.0

### To Reproduce

1. Set default groupId and artifactId and service URL(eg: http://localhost:8080) 
2. Open Command Palette, execute the command `Spring Initializr: Generate a Maven Project`
3. press <Enter> to use default groupId and artifactId

### Current behavior
Not prompt error message when connect site failed, only show error in toggle developer tools
![image](https://user-images.githubusercontent.com/41051257/90726299-1165c000-e2f4-11ea-9d57-add4ecb77d05.png)

### Expect behavior
![image](https://user-images.githubusercontent.com/41051257/90726198-e8452f80-e2f3-11ea-9db4-d13185d0d382.png)

**Comment by Eskibear** [comment]
is it a regression introduced by this version?

**Comment by Eskibear** [comment]
https://github.com/microsoft/vscode-spring-initializr/blob/d2718df42bbf88fa370d2c3cff8489df22cf0942/src/handler/SpecifyBootVersionStep.ts#L42

the error was eaten.


@CsCherrYY Another UX issue related is, after you pick a service url, it doesn't verify the availability immediately, but failed after you fill in the blanks for several steps. That's not good.
