### ISSUE TITLE
spring-initializr start error

### ISSUE THREAD

**Issue by mr-tan4** [microsoft/vscode-spring-initializr#167]
system:
 mac Big Sur
version: 11.1 (20C69)
vscode:
 Version: 1.52.0
spring-initializr-java-support 
  version:0.6.1

do spring-initializr create maven project error

![图片](https://user-images.githubusercontent.com/15813848/102297947-30671c80-3f8b-11eb-8446-41ab8aec0d65.png)

developer toggler tools console
![图片](https://user-images.githubusercontent.com/15813848/102298116-81771080-3f8b-11eb-9ff2-dce99e08ae67.png)

**Comment by Eskibear** [comment]
It can be networking issue. Can you try below command in terminal, see if the response is correct in JSON format?

```
curl -i -H "Accept: application/vnd.initializr.v2.2+json,application/vnd.initializr.v2.1+json;q=0.9" https://start.spring.io
```

FYI, below is my case, status code is 200, and the response is correct.
```
$ curl -i -H "Accept: application/vnd.initializr.v2.2+json,application/vnd.initializr.v2.1+json;q=0.9" https://start.spring.io
HTTP/2 200 
date: Wed, 16 Dec 2020 06:21:24 GMT
content-type: application/vnd.initializr.v2.2+json
content-length: 45884
set-cookie: __cfduid=da40cf5e297e01b0baa9b75b35eebea2b1608099684; expires=Fri, 15-Jan-21 06:21:24 GMT; path=/; domain=.spring.io; HttpOnly; SameSite=Lax; Secure
etag: "68dfa97aea2c9cb52d5f0acb71e579ba"
vary: Accept
cache-control: max-age=7200
via: 1.1 google
cf-cache-status: DYNAMIC
cf-request-id: 070bcef6cf0000dcd229308000000001
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
strict-transport-security: max-age=15552000; includeSubDomains
server: cloudflare
cf-ray: 60264dd14fe6dcd2-SIN

{"_links":{"maven-project":{"href":"https://start.....(omitted)...}
```

**Comment by mr-tan4** [comment]
You are right, when I visit https://start.spring.io, I am prompted that secondary authentication is required
You are right, when I visit https://start.spring.io, I am prompted that secondary authentication is required
You are right, when I visit https://start.spring.io, I am prompted that secondary authentication is required
You are right, when I visit https://start.spring.io, suggesting the need for secondary certification
You are right, when I visit https://start.spring.io, suggesting the need for secondary certification
