### ISSUE TITLE
Fail to create a project. Error: Failed to fetch metadata.

### ISSUE THREAD

**Issue by lancerXXXX** [microsoft/vscode-spring-initializr#168]
![image](https://user-images.githubusercontent.com/42160297/105664195-0c461600-5f0f-11eb-9d89-9ab616259088.png)

I try to use spring boot on vscode with WSL, but there is something wrong

![image](https://user-images.githubusercontent.com/42160297/105664181-06503500-5f0f-11eb-9692-3f705db741e3.png)

**Comment by Eskibear** [comment]
Please check your networking status. See https://github.com/microsoft/vscode-spring-initializr/issues/167 for reference.

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/105669791-e9216380-5f1a-11eb-9e19-668420ab5ef4.png)


![image](https://user-images.githubusercontent.com/42160297/105669835-fa6a7000-5f1a-11eb-8213-69b4048addd4.png)

maybe this problem is related to WSL

it works well on windows10

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/105670005-4a493700-5f1b-11eb-8a38-e2cc2add876c.png)

maybe this problem is related to WSL2

**Comment by lancerXXXX** [comment]
it still cannot work

**Comment by Eskibear** [comment]
> maybe this problem is related to WSL2

I don't think so. It's working well in my WSL 2 environment. Can you check if there's any detailed error messages in console of  "Developer tools"? The entry is from command palette.

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/105672839-10c6fa80-5f20-11eb-9151-0d58a18ecd2f.png)

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/105672945-3e13a880-5f20-11eb-8242-85b1786a59a5.png)

maybe my setting about maven is wrong

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/105673032-63a0b200-5f20-11eb-886b-5788e38544a3.png)

**Comment by Eskibear** [comment]
This extension has nothing to do with Maven/Java stuffs. The error was about failing to retrieve or parse responses from start.spring.io...  

You can:
1. Press F1 or Ctrl+shift+P to open command palette.
2. choose "Developer: toggle developer tools"
3. choose "Console" tab, see if there's any related error messages

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/105675451-1d4d5200-5f24-11eb-8e84-14073355e23d.png)

**Comment by Eskibear** [comment]
Please check you networking status including system proxies. Are you hosting a proxy server on `127.0.01:7890`?

**Comment by lancerXXXX** [comment]
![image](https://user-images.githubusercontent.com/42160297/105679988-26412200-5f2a-11eb-81d4-5d9ef7bda969.png)


Oh, it does

i tried to change the port to 9999

the error message will change to 9999
![image](https://user-images.githubusercontent.com/42160297/105680214-60aabf00-5f2a-11eb-8e77-3e82325f68af.png)

but if I close it 

the extension works well

thank you so much

**Comment by DachuanZhao** [comment]
> Please check you networking status including system proxies. Are you hosting a proxy server on `127.0.01:7890`?

Could you please let the plugin work when networking status is including system proxies ?

**Comment by Eskibear** [comment]
Dealing with proxies can be complex, as vscode also has some settings related to proxies. In unix-like systems, environment variables like `http_proxy` also affects netwoking. So PR is welcome if you are interested in it and are willing to find a systematic solution for the cases.

**Comment by xinmu123456** [comment]
I had a very similar experience to yours and my final solution was to use a mirror site

`https://start.aliyun.com`

![image](https://user-images.githubusercontent.com/96987156/203074243-b6fedea5-ce9f-4de6-9159-53ed6a75835e.png)

And use it when you create a new springboot project
