### ISSUE TITLE
Fail to create a project. Error: Failed to fetch metadata.

### ISSUE THREAD

**Issue by jinweiLiu** [microsoft/vscode-spring-initializr#183]
did anyone meet this problem? how can I fixed it? Thanks!

**Comment by Eskibear** [comment]
Possibly networking issue. Can you access https://start.spring.io/ ？

**Comment by jinweiLiu** [comment]
yes I ca-------- 原始邮件 --------发件人： Yan Zhang ***@***.***>日期： 2021年5月6日周四 13:03收件人： microsoft/vscode-spring-initializr ***@***.***>抄送： jinweiLiu ***@***.***>, Author ***@***.***>主    题： Re: [microsoft/vscode-spring-initializr] Fail to create a project. Error: Failed to fetch metadata. (#183)

Possibly networking issue. Can you access https://start.spring.io/ ？

**Comment by Eskibear** [comment]
please open Help -> Toggle Developer Tools -> Console , see if there's any detailed logs/callstack.

**Comment by jinweiLiu** [comment]
![image](https://user-images.githubusercontent.com/39424633/117247657-452c4a00-ae71-11eb-8a65-37e14b914d02.png)

**Comment by Eskibear** [comment]
104.20.5.247 is the ip address of domain start.spring.io

> ETIMEDOUT (Operation timed out): A connect or send request failed because the connected party did not properly respond after a period of time. 

It's networking issue, at least vscode cannot connect to the ip address directly (if you didn't configure any proxy for vscode). Considering you just mentioned you can access start.spring.io webpage, please check proxy setting of your browser/system.

**Comment by jinweiLiu** [comment]
> 104.20.5.247 is the ip address of domain start.spring.io
> 
> > ETIMEDOUT (Operation timed out): A connect or send request failed because the connected party did not properly respond after a period of time.
> 
> It's networking issue, at least vscode cannot connect to the ip address directly (if you didn't configure any proxy for vscode). Considering you just mentioned you can access start.spring.io webpage, please check proxy setting of your browser/system.

ok! thanks a lot
