### ISSUE TITLE
Failed to create a project. end of central directory record signature not found

### ISSUE THREAD

**Issue by SpaceMonkeee** [microsoft/vscode-spring-initializr#218]
Getting this error with most current version, what can I do to fix it?

![image](https://user-images.githubusercontent.com/117305862/199561265-448cbf16-469c-4953-b02f-f4db94306f39.png)

**Comment by Eskibear** [comment]
Probably networking issue. The error is thrown during unziping the project template downloaded from start.spring.io. A broken file I guess.

**Comment by SpaceMonkeee** [comment]
Looks like it, I can't download manually from https://start.spring.io/ either. It says could not connect to server

**Comment by Eskibear** [comment]
Please switch to a stable networking connection where you can connect to start.spring.io, or you can specify a third party service with setting `spring.initializr.serviceUrl`. 

I'm closing it.
