### ISSUE TITLE
Invalid Group ID

### ISSUE THREAD

**Issue by Pizaan22** [microsoft/vscode-spring-initializr#221]
Recently, I have been facing this issue whenever I try to create a new maven project with the spring intializer extension and try to put my group Id and separate it with a decimal, the error pops up which is fine and is expected however, it throws out the cursor from the input box and it wouldn't allow me to type anything later. I have tried to reinstall the extension and that doesn't work as well. Help will be much appreciated as this extension makes my life a lot easier. Thanks in advance!

**Comment by Pizaan22** [comment]
> Already fixed in v0.11.1. Please update and have a try.
> 
> See [microsoft/vscode-maven#896](https://github.com/microsoft/vscode-maven/issues/896) for more details.

How do I access that code to change in the value?

**Comment by Eskibear** [comment]
We already fixed it. You just update spring initializr extension to v0.11.1, then everything should be fine.

**Comment by Pizaan22** [comment]
Works fine now!
