### ISSUE TITLE
Allow user to select Spring Boot version

### ISSUE THREAD

**Issue by dsyer** [Microsoft/vscode-spring-initializr#24]
... and other things. But that's the one that I miss the most.

**Comment by Matthew-Dong** [comment]
Greetings,

@dsyer , thanks for the feedback. We plan to support SB version selection in the next milestone. 

Also, feel free to let us know other parts that you miss.

**Comment by Eskibear** [comment]
Agree, available dependencies are also related to the version.

Most of other things can be easily modified in `pom.xml` or `build.gradle`. I'd rather not to use dropdown inputboxes step by step, which probably hurts the user experience.

**Comment by Eskibear** [comment]
fixed in #31 , before selecting dependencies, it first requests you to choose a version, then filter compatible deps for you.
