### ISSUE TITLE
Using Add Starters will repeatedly add dependencies

### ISSUE THREAD

**Issue by LuckySgr** [microsoft/vscode-spring-initializr#242]
This is the result(On the left is the one before add，On the right is after add)

PS: Every time add starters are used, dependencies will be added

![image](https://github.com/microsoft/vscode-spring-initializr/assets/51776225/d905bdab-862c-42f3-a7ab-39486c7a37cf)

**Comment by oubrikyoussef** [comment]
same here
![image](https://github.com/user-attachments/assets/7b658e84-9f7c-44da-8790-95e91f012cd9)
![image](https://github.com/user-attachments/assets/6931f0e5-c0cb-412c-9a10-04dd6b74d8ca)
after adding spring data jpa and posgresql driver
![image](https://github.com/user-attachments/assets/2624d371-296b-4071-8ac9-56ee66625690)

**Comment by KajP** [comment]
I have the same issue when trying to add new dependencies whether I create the project using Spring Initalizr inside VS Code or import an existing project.

**Comment by BoykoAlex** [comment]
Do you mind pasting the entire POM of the original project to which starters are being added please?
I'm trying to reproduce it but with no luck so far... Perhaps there is something in the XML that prevents from finding the existing `<dependencies>` element

**Comment by oubrikyoussef** [comment]
Thank you for your response Below is the complete `pom.xml` file for the original project:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.3.1</version>
		<relativePath />
		<!-- lookup parent from repository -->
	</parent>
	<groupId>com.openclassrooms</groupId>
	<artifactId>watchlist</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>watchlist</name>
	<description>Demo project for Spring Boot</description>
	<url />
	<licenses>
		<license />
	</licenses>
	<developers>
		<developer />
	</developers>
	<scm>
		<connection />
		<developerConnection />
		<tag />
		<url />
	</scm>
	<properties>
		<java.version>22</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.13.2</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-actuator</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>
```

I also attempted to add a new dependency, but instead of appending to the existing `<dependencies>` block, a **new `<dependencies>` tag** was created, and the chosen dependency was added within it.

![Screenshot of the new dependencies tag](https://github.com/user-attachments/assets/be75d983-d45f-4a2f-b4fb-f5d5b2f6aa23)

![Screenshot showing the added dependency](https://github.com/user-attachments/assets/f8042480-93ef-4976-b8a1-22ae8e66d325)

Let me know if you need more details or have any thoughts on resolving this behavior.

**Comment by oubrikyoussef** [comment]
Thank you for your guidance! I replaced the self-closing tags, including <url /> under the <project> tag, with opening and closing tags , and it resolved the issue. I appreciate your help

**Comment by oubrikyoussef** [comment]
Thank you for your guidance! I replaced the self-closing tags, including <url /> under the <project> tag, with opening and closing tags , and it resolved the issue. I appreciate your help
