### ISSUE TITLE
please support filtering deependencies by keywords for the project

### ISSUE THREAD

**Issue by joshlong** [Microsoft/vscode-spring-initializr#26]
this way I could type in a word and get a more relevant match

**Comment by dsyer** [comment]
Example: in the web UI if you type "template" into the combo box you get 4 hits. In VSCode it is only 1 (the one that has "template" in the name I guess).

**Comment by Eskibear** [comment]
@dsyer Yes, by default it only includes the `name` when filtering the picks. Setting `matchOnDetail: true` would fix this.

Note that the filtering logic is handled by VSCode, we only specify where to match. The results are sometimes strange, e.g.

"templat" gets 4 hits:
![image](https://user-images.githubusercontent.com/2351748/35202226-6721ef7e-ff5c-11e7-83ab-d88d753e56f6.png)

"template" gets 3 hits:
![image](https://user-images.githubusercontent.com/2351748/35202241-785d3d70-ff5c-11e7-8f2f-30c137ac21b1.png)

I've no idea why `Thymeleaf` doesn't match, maybe I should open a issue in vscode repo.

**Comment by Eskibear** [comment]
Or we can also enable `matchOnDescription`.

![image](https://user-images.githubusercontent.com/2351748/35203711-8ba69a36-ff64-11e7-8878-9aa1665bb4c9.png)

The 2-line textbox includes 3 parts, i.e.
```
[ name ] [ description ]
[ detail               ]
```

**Comment by snicoll** [comment]
@Eskibear matching also on description is a big +1 on my end. That's what the web UI does at the moment.

**Comment by Eskibear** [comment]
@snicoll  
matching on description also makes good sense for me. Tend to fix this in #30 .

BTW, I find WebUI also supports filtering by `keywords` if there is one, but here with APIs of VSCode we cannot do that unless we explicitly show the keywords. But anyway, I still can filter them by "group" and "description", keywords are not that important to my mind.

**Comment by dsyer** [comment]
IMO keywords are important (otherwise the feature wouldn't exist). Maybe it wouldn't be that hard to display them along with the description?

**Comment by snicoll** [comment]
> IMO keywords are important (otherwise the feature wouldn't exist)

It is important in the context of the Web UI searcher that is limited (we needed something to narrow down as we limit the number of results to 5 items). 

Keywords are not part of the metadata so there is no way to get that information currently. I disagree that they are important globally for the very reason why they exist in the first place and that other clients do not suffer from any visible limitation (the IJ searcher is more poweful for instance and doesn't need to discriminate as we do).

**Comment by Eskibear** [comment]
> Keywords are not part of the metadata

Exactly, dependencies are oganized by groups in metadata, without `keywords` .

> so there is no way to get that information currently. 

I find this API ( https://start.spring.io/ui/dependencies.json?version=1.5.9.RELEASE ) contains flatten dependencies available for a specified bootVersion.
`keywords` can also be found here, but this `/ui/dependencies.json` is not listed in the [documentation](https://docs.spring.io/initializr/docs/current/reference/htmlsingle/#api-guide).

So I'm not sure whether I should rely on this API or not.

**Comment by Eskibear** [comment]
> Maybe it wouldn't be that hard to display them along with the description?

As I mentioned, we can specify content of a dropdown entry in 3 places with current VSCode API.
```
[ A ] [ B ]
[   C     ]
```
For the moment, `name`, `group` and `description` are put in those places.
* A: name, e.g.  DevTools, Security
* B: group, e.g. Core, Web
* C: description 

@dsyer Do you mean displaying description + keywords in C slot to enhance filtering? I think it's not that natrual.

**Comment by snicoll** [comment]
> So I'm not sure whether I should rely on this API or not.

You should not. It isn't documented and the `/ui` part of it (attempts to) make it clear it's not supposed to be consumed by other clients. It can change at any time in a non backward compatible way.

**Comment by Eskibear** [comment]
@snicoll That makes sense. 

BTW, to allow bootVersion selection (#24), without the convenient `/ui`,  in order to get available dependencies for the selected bootVersion, it seems I have to parse `dependencies` from raw metadata, verify `versionRange`. Right?

**Comment by snicoll** [comment]
I am not sure what you mean by "raw metadata" but yes, you have a single document that contains the necessary information that  lets you disable things that aren't available in a given Spring Boot version. You may want to offer auto-completion even if it's disabled with a special visual effect or something.

**Comment by Eskibear** [comment]
`keywords` not in metadata, and matching on description is supported. So I'll close this issue.
