### ISSUE TITLE
Remember the groupid/artifactid between runs.

### ISSUE THREAD

**Issue by aclement** [Microsoft/vscode-spring-initializr#28]
If i re-run the generation a number of times I am probably wanting to generate a series of related projects - likely with a common groupId, possibly with related artifactIds. It should remember what I used before and pre-populate the first 2 stages with that data (that I can edit).

**Comment by snicoll** [comment]
I am feeling all bit differently about that. Keeping the last recorded value seems odd to me. Especially the artifactId. 

My preference would be a preference pane where you could set default values.

**Comment by aclement** [comment]
Preferences are likely to be in a json document rather than a panel (like other vscode settings), but yes, they could be in there.  I agree artifact id is a little odd but i felt if you kept one you'd keep the other for consistency. Happy to go with preferences - as long as there is a way to avoid repeatedly typing the same thing if I'm in an enterprise where some of these are often the same/similar.

**Comment by Eskibear** [comment]
fixed in #31 , use `"spring.initializr.defaultGroupId"` to specify the value.
