### ISSUE TITLE
An unknown error occured

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-spring-initializr#33]
Build used: build36
1. Install the extension build
2. Open VS Code without opening any folder.
3. Open Command Palette, execute command Spring Initializr: Generate a Maven Project.
4. Input a valid Group Id, press Enter.
5. Input a valid Artifact Id, press Enter.
6. Select a spring boot version

Error occurred:
![image](https://user-images.githubusercontent.com/22470312/35549368-2698909c-05c0-11e8-8a23-dd171d912fa7.png)

**Comment by Eskibear** [comment]
confirmed, unhandled NPE.

**Comment by Eskibear** [comment]
please help to verify.

**Comment by bsaby** [comment]
Test passed.
Build used: build38
