### ISSUE TITLE
Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-spring-initializr#35]
Build used: build38

1. Open VS Code without opening any folder.
2. Open Command Palette, execute command Spring Initializr: Generate a Maven Project.
3. Input a valid Group Id, press Enter.
4. Input a valid Artifact Id, press Enter.
5. Then show the spring boot version view, Press Esc

![image](https://user-images.githubusercontent.com/22470312/35553014-12b58754-05d1-11e8-8b1d-efff8686b77b.png)

**Comment by Eskibear** [comment]
fixed, check build 39

**Comment by bsaby** [comment]
Test passed.
Build used: build 39
