### ISSUE TITLE
The spring boot version will not change by the version selection

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-spring-initializr#36]
The spring boot version is always 1.5.9-RELEASE in the pom.xml / build.gradle file
![image](https://user-images.githubusercontent.com/22470312/35554774-dce7068c-05d7-11e8-8061-979728dc7b13.png)
![image](https://user-images.githubusercontent.com/22470312/35554775-dee44120-05d7-11e8-9fb3-3e9bae5589a5.png)

**Comment by Eskibear** [comment]
fixed, check build 39

**Comment by bsaby** [comment]
Test passed. 
Build used: build39
