### ISSUE TITLE
Should add the version selection step in the steps message

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-spring-initializr#39]
![image](https://user-images.githubusercontent.com/22470312/35555400-0348994c-05da-11e8-83ff-04b5d3f43346.png)
![image](https://user-images.githubusercontent.com/22470312/35555404-051cc590-05da-11e8-8169-20e55bf4a17a.png)
![image](https://user-images.githubusercontent.com/22470312/35555405-06d0aa78-05da-11e8-9409-c39ed4723191.png)
![image](https://user-images.githubusercontent.com/22470312/35555408-0845a426-05da-11e8-9ed3-c4dd9383d3be.png)

In addition, It is better to add a hint to tell the user what will do at this step.

**Comment by Eskibear** [comment]
check dev build 41

**Comment by bsaby** [comment]
Test passed.
Build used: build41
