### ISSUE TITLE
Proxy?!

### ISSUE THREAD

**Issue by stejsoftware** [Microsoft/vscode-spring-initializr#50]
This extension is not using my proxy settings.

```
[2018-03-30 15:30:11.474] [renderer1] [error] connect ETIMEDOUT 104.17.46.2:443: Error: connect ETIMEDOUT 104.17.46.2:443
	at Object.exports._errnoException (util.js:1050:11)
	at exports._exceptionWithHostPort (util.js:1073:20)
	at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1097:14)
```

**Comment by Eskibear** [comment]
where did you set your proxy?

And I don't think vscode-maven should handle the proxy. In my opinion, this extension only helps to send requests, and users can have flexible ways to manage where the request goes.

E.g. you may have a global pac file indicating some the request goes via your proxy if their destination is 104.17.46.2 

BTW, https://104.17.46.2/ returns code 403,  and http://104.17.46.2/ (plain http, no s) tells that my IP is restricted. So is there any possibility that it's because you wrongly set the service url?

**Comment by stejsoftware** [comment]
PS C:\> nslookup start.spring.io
Server:  r-dc-016c-03.lm.lmig.com
Address:  10.103.80.76

Non-authoritative answer:
Name:    start.spring.io
Addresses:  2400:cb00:2048:1::6811:2f02
          2400:cb00:2048:1::6811:2e02
          104.17.47.2
          104.17.46.2

PS C:\>

**Comment by Eskibear** [comment]
>   // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
  "http.proxy": "",

About the proxy, currently we don't take `http.proxy` into consideration. Only system-wide proxy settings take effect.

Proxy setting is a complicated problem. Say if you have specified the system proxy **A**, and have also specified an environment variable `http_proxy` **B**, and in VSCode you set value of `http.proxy` to **C**, then which one of them should finally take effect?
Need further discussion.

**Comment by ElapsedSoul** [comment]
> > // The proxy setting to use. If not set will be taken from the http_proxy and https_proxy environment variables
> > "http.proxy": "",
> 
> About the proxy, currently we don't take `http.proxy` into consideration. Only system-wide proxy settings take effect.
> 
> Proxy setting is a complicated problem. Say if you have specified the system proxy **A**, and have also specified an environment variable `http_proxy` **B**, and in VSCode you set value of `http.proxy` to **C**, then which one of them should finally take effect? Need further discussion.

Usually, most developers will set A,B,C the same.
Or you can announce A or B or C or even D to use ,then we set it.
Having one setting is more important than discussion which one to choose.
