### ISSUE TITLE
Failed to build after removing security dependency

### ISSUE THREAD

**Issue by bsaby** [Microsoft/vscode-spring-initializr#59]
1. Generate a maven project , select  "Security" dependency.
2. Open pom.xml file, verify current value of dependencies node.
3. Right click on the editing area of the file, choose Edit starters.
4. In the QuickPick box, unselect "Security", and proceed following the prompt messages.
5. mvn package
![image](https://user-images.githubusercontent.com/22470312/39233755-eb5e2682-48a3-11e8-9b11-ae7769b848ed.png)

**Comment by Eskibear** [comment]
same issue in STS 3.9.1

**Comment by Eskibear** [comment]
relevant issue : https://github.com/spring-projects/sts4/issues/52
