### ISSUE TITLE
mvnw missing execute permission 

### ISSUE THREAD

**Issue by Eskibear** [Microsoft/vscode-spring-initializr#66]
In MacOSX, file `mvnw` doesn't have execute permission. But if I downloads a zip from start.spring.io, and unzip if myself, it works well.

**Comment by Eskibear** [comment]
Reason: the package used to unzip the .zip file doesn't preserve file permissions. 
See: https://github.com/mhr3/unzip-stream/issues/18

**Comment by lrkwz** [comment]
Same on ubuntu

**Comment by Eskibear** [comment]
@lrkwz I think we have to manually execute `chmod +x ./mvnw` for the moment before we find a way to preserve permission. 🤦‍♂️

**Comment by Eskibear** [comment]
Maybe this lib works, I'll try it later. 

https://github.com/maxogden/extract-zip
