### ISSUE TITLE
Support packaging type of WAR when scaffolding a project 

### ISSUE THREAD

**Issue by Matthew-Dong** [Microsoft/vscode-spring-initializr#68]
![image](https://user-images.githubusercontent.com/7653539/44964834-11345480-af65-11e8-94d8-b833aaac40c1.png)

**Comment by Matthew-Dong** [comment]
We'd like to recommend using Spring Initializr extension in VS Code as the entry point for Java developer experience when scaffolding a project. However, it only supports to generate a JAR project, which means large numbers of developers using Tomcat have to bring their own project to VS Code. This also caused an inconsistency in the tutorial.

**Comment by Eskibear** [comment]
@Matthew-Dong I thought the only difference was the value of "<packaging>". But it looks for `WAR` packaging, it adds following block in the pom.xml:
```xml
	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
```

It's feasible to allow users to select packaging type, but we should decide where to insert this step. 
Current workflow is: 

* Choose Maven/Gradle with different commands
* Select Language
* Input GroupId.
* Input ArtifactId.
* Select dependencies. 
* Select a local folder to place extracted files.

**Comment by Eskibear** [comment]
Or do you prefer similar ways to handle language?

E.g. we can have a configuration instead of letting users to bother an extras step to select packaging type. By default, it can be `JAR`, if you want to generate `WAR`, use the settings. 
```
  // Default packaging.
  "spring.initializr.defaultPackaging": "JAR",    // <--- candidates are "JAR", "WAR"
```

**Comment by Eskibear** [comment]
implemented.
