### ISSUE TITLE
Final dialog is not responding to mouse input on Linux

### ISSUE THREAD

**Issue by edgarmedrano** [Microsoft/vscode-spring-initializr#69]
Hi, i'm experiencing a problem like the one mentioned at https://github.com/electron/electron/issues/9942 with the final dialog of the Initializr.

Please let me know if there is a workaround for users. I'm using Ubuntu 18.04 LTS.

**Comment by Eskibear** [comment]
I can think of a nasty workaround, if you are willing to directly modify the js code of the extension.  

#### Workaround
By changing some js code, you are able to type the target folder path by yourself, there would be no check for your input. 

#### Steps
1. Open `~/.vscode/extensions/vscjava.vscode-spring-initializr-0.3.0/out/Routines.js`

2. Find `// Step: Choose target folder` in Line 109. Change javascript code in this step to the following:
```javascript
// Step: Choose target folder
const outputUriFilepath = yield VSCodeUI_1.VSCodeUI.getFromInputBox({ placeHolder: "Generate into this folder" });
if (!outputUriFilepath) { 
    return;
}
const outputUri = vscode.Uri.file(outputUriFilepath);
finishStep(session, stepTargetFolder);
```

3. Reload window.

4. Let me know if it works.

**Comment by edgarmedrano** [comment]
Thanks for the solution, it works. Here's an improved version:

```javascript
// Step: Choose target folder
/*
const outputUri = yield VSCodeUI_1.VSCodeUI.openDialogForFolder({ openLabel: "Generate into this folder" });
if (!outputUri) {
    return;
}
finishStep(session, stepTargetFolder);
*/
const BASE_DIR = "/home/username/projects_dir/spring/"
const outputUriFilepath = yield VSCodeUI_1.VSCodeUI.getFromInputBox({ prompt: "Generate into this folder", value: BASE_DIR });
if (!outputUriFilepath) { 
    return;
}
const outputUri = vscode.Uri.file(outputUriFilepath);
finishStep(session, stepTargetFolder);
```
