### ISSUE TITLE
Provide a simple way to run/debug Spring Boot apps

### ISSUE THREAD

**Issue by brunoborges** [Microsoft/vscode-spring-initializr#73]
Currently, it requires user to go to Terminal and use the Maven Spring Boot plugin `mvn spring-boot:run`. It also requires extra setup for debugging.

**Comment by Eskibear** [comment]
For Maven Spring Boot projects, it will be good if the extension "Maven for Java" can identify plugin goals as mentioned in  https://github.com/Microsoft/vscode-maven/issues/126 .

**Comment by Eskibear** [comment]
I'm closing it, as there're already two simple alternatives now:
* Execute plugin goal for Maven Spring Boot projects. (See [Maven for Java](https://github.com/Microsoft/vscode-maven/blob/v0.12.0/images/plugin.gif) )
* Shortcuts to start/debug Spring Boot projects. (See [Spring Boot Dashboard](https://github.com/Microsoft/vscode-spring-boot-dashboard))
