### ISSUE TITLE
Command to expose 'Edit Starters' functionality

### ISSUE THREAD

**Issue by akaroml** [Microsoft/vscode-spring-initializr#79]
'Edit Starters' is an essential feature. The current entry of this functionality is hard to find - open pom.xml and right click.

A command needs to be added to VS Code - Spring Initializr: Edit Starters
The target pom.xml can be in different status. And here are some common scenarios:
1. A pom.xml is opened and active - work with that file directly
2. A project has only one pom.xml - work with that file directly
3. A project has more than one pom.xml - list all the pom files with hierarchical representation, let user choose one
4. Regarding 2 and 3, when the active editor is NOT a pom.xml, open the target file and make it active

**Comment by Eskibear** [comment]
Fixed in #83
