### ISSUE TITLE
Edit Starts to ask less questions 

### ISSUE THREAD

**Issue by akaroml** [microsoft/vscode-spring-initializr#80]
At the end of the procedure, do not ask the users to 'Proceed'.

Suggested way:
1. Open pom.xml and make it active
2. Apply code changes to it WITHOUT saving

In this way, users are aware of the changes and can choose to Save or Cmd + Z

**Comment by Eskibear** [comment]
Now it's using WorkspaceEdit instead of physically modifying pom.xml :
- [x] Open pom.xml and make it active
- [x] Apply code changes to it WITHOUT saving
