### ISSUE TITLE
The input rules of group Id and artifact Id should be informed for user

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-spring-initializr#87]
Generate a Maven Project, the user was not told the entry rule of Group Id and Artifact Id. 

Result:
![image](https://user-images.githubusercontent.com/41051257/47208710-1c322f80-d3c1-11e8-9f51-1e7777ab0bc4.png)

**Comment by Eskibear** [comment]
I tried start.spring.io, they don't have a check for it, the project simply fills whatever you input into the groupId. So I don't have an accurate regexp for it. 
Currently we have some simple checks, and I think that's enough. No plan to support it for the moment.
