### ISSUE TITLE
Generate a  Project: Alert the user to ensure that the project of the same name is overwritten

### ISSUE THREAD

**Issue by ZhengJun003** [Microsoft/vscode-spring-initializr#88]
Generate a  Maven or Gradle Project, Alert the user to ensure that the project of the same name is overwritten。

For example：
![image](https://user-images.githubusercontent.com/41051257/47212428-b5b20f00-d3ca-11e8-87f2-79ee7cda560c.png)

**Comment by Eskibear** [comment]
fixed in #90
